on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - 'pypy3.10'
        django:
          - '4.2'
          - '5.0'
          - '5.1'
    name: Python ${{ matrix.python }} / Django ${{ matrix.django }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Setup django ${{ matrix.django }}
        run: pip install "django<=${{ matrix.django }}"
      - name: Run tests
        run: python -m mathfilters.tests

  check-formatting:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
      - uses: actions/checkout@v4
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: "mathfilters --check --diff"
